#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/vim-gtk vim-gui-common 2:8.0.1451-1\~ vim-gtk -- "$@"
# End automatically added section
